### ISSUE TITLE
run.py works, but running the test directly (ctest or command line) does not..

### ISSUE THREAD

**Issue by slremy** [SwissTPH/openmalaria#190] opened 2017-08-05 20:18 UTC
For the life of me, I can't make sense of this.. according to the python script, it's running the same executable commands as the unit tests.. but the tests fail when run via ctest..

So far, all of the tests that fail pass when run via run.py.
```
[ 95%]	Checkpoint test: checkpoint written; exiting...
OpenMalaria: No such file or directory
Assertion failed: (measure < measure_map.size()), function report, file /Users/sekou/Documents/source/oli/openmalaria-git/model/mon/mon.cpp, line 292.
[0;33mFri, 04 Aug 2017 18:09:19	[1;33m/Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml
[0;32m  /Users/sekou/Documents/source/oli/openmalaria-git/build2/openMalaria --deprecation-warnings --resource-path /Users/sekou/Documents/source/oli/openmalaria-git/test --scenario /Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml --checkpoint[0;00m
[0;32m  /Users/sekou/Documents/source/oli/openmalaria-git/build2/openMalaria --deprecation-warnings --resource-path /Users/sekou/Documents/source/oli/openmalaria-git/test --scenario /Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml --checkpoint[0;00m
[1;31mNon-zero exit status: -6
[0;00m
<end of output>
Test time =  48.75 sec
----------------------------------------------------------
Test Failed.
"Empirical" end time: Aug 04 18:10 EAT
"Empirical" time elapsed: 00:00:48
----------------------------------------------------------

```

but 

```
python test/run.py EMPIRICAL
Fri, 04 Aug 2017 18:45:44	/Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEMPIRICAL.xml
  /Users/sekou/Documents/source/oli/openmalaria-git/build2/openMalaria --deprecation-warnings --resource-path /Users/sekou/Documents/source/oli/openmalaria-git/test --scenario /Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEMPIRICAL.xml
BoincWrapper: not using BOINC
Deprecation warning: model option INCLUDES_PK_PD is no longer used
Deprecation warning: monitoring/surveys: specification of "diagnostic" is suggested over "detectionLimit"
Deprecation warning: time specified via duration "3650" where a date could be used; recommended to use a date (e.g. 2011-12-20)
Deprecation warning: duration "3650" specified without unit; it is recommended to do so (e.g. 5d or 1t or 0.5y)
Deprecation warning: duration "28" specified without unit; it is recommended to do so (e.g. 5d or 1t)
Deprecation warning: specification of the diagnostic used by the Neonatal Mortality model is recommended (model/clinical/neonatalMortality)
[ 99%]	sim end
Total/allowed infections: 155809/155809	(0% prevented)
Human updates/total calls: 6282549/7300200	(13.94% skipped)
Done in 21.5596790314 seconds
  compareOutput.py /Users/sekou/Documents/source/oli/openmalaria-git/test/expected/outputEMPIRICAL.txt /Users/sekou/Documents/source/oli/openmalaria-git/build2/test/EMPIRICAL-nePXxg/output.txt 0
output.txt files are identical
```

`  1/33 Test  #1: unittest .........................***Not Run   0.00 sec
      Start  2: 1
      Start  3: 4
      Start  4: 5
      Start  5: 6
      Start  6: 9
      Start  7: 10
      Start  8: 11
      Start  9: 12
 2/33 Test  #6: 9 ................................   Passed    2.45 sec
 3/33 Test  #7: 10 ...............................***Failed    2.87 sec
      Start 10: 2ITNs
      Start 11: Cohort
 4/33 Test  #5: 6 ................................***Failed    5.42 sec
 5/33 Test  #2: 1 ................................   Passed    5.43 sec
 6/33 Test  #4: 5 ................................***Failed    5.84 sec
      Start 12: EffectiveDrug
      Start 13: Empirical
      Start 14: ESTS
 7/33 Test  #8: 11 ...............................   Passed    8.71 sec
      Start 15: Genotypes
 8/33 Test  #9: 12 ...............................   Passed   14.82 sec
      Start 16: IRS30
 9/33 Test  #3: 4 ................................   Passed   24.91 sec
      Start 17: KK_20150612
10/33 Test #14: ESTS .............................***Failed   22.76 sec
      Start 18: Molineaux
11/33 Test #11: Cohort ...........................***Failed   26.74 sec
      Start 19: MolPairwise
12/33 Test #13: Empirical ........................***Failed   28.80 sec
13/33 Test #10: 2ITNs ............................   Passed   31.77 sec
      Start 20: MSAT
      Start 21: NamawalaArabiensis
14/33 Test #12: EffectiveDrug ....................***Failed   33.21 sec
      Start 22: NoInterv
15/33 Test #19: MolPairwise ......................***Failed   15.37 sec
      Start 23: NoMPDLarviciding
16/33 Test #21: NamawalaArabiensis ...............   Passed   11.67 sec
      Start 24: Penny
17/33 Test #16: IRS30 ............................   Passed   32.71 sec
      Start 25: Rach5IC
18/33 Test #17: KK_20150612 ......................***Failed   31.30 sec
      Start 26: SimpleMPDLarviciding
19/33 Test #22: NoInterv .........................***Failed   22.16 sec
      Start 27: SimpleMPDTest
20/33 Test #20: MSAT .............................***Failed   37.33 sec
      Start 28: SubPopRemoval
21/33 Test #23: NoMPDLarviciding .................***Failed   26.59 sec
      Start 29: TrapTest
22/33 Test #27: SimpleMPDTest ....................   Passed   16.90 sec
      Start 30: VecFullTest
23/33 Test #18: Molineaux ........................***Failed   51.88 sec
      Start 31: VecMonthly
24/33 Test #25: Rach5IC ..........................   Passed   32.65 sec
      Start 32: VecTest
25/33 Test #26: SimpleMPDLarviciding .............***Failed   30.44 sec
      Start 33: Vivax
26/33 Test #31: VecMonthly .......................***Failed   10.06 sec
27/33 Test #32: VecTest ..........................   Passed   15.42 sec
28/33 Test #28: SubPopRemoval ....................   Passed   24.76 sec
29/33 Test #29: TrapTest .........................***Failed   27.03 sec
30/33 Test #33: Vivax ............................***Failed   14.04 sec
31/33 Test #30: VecFullTest ......................***Failed   25.47 sec
32/33 Test #24: Penny ............................***Failed   65.62 sec
33/33 Test #15: Genotypes ........................***Failed  122.38 sec

36% tests passed, 21 tests failed out of 33

Total Test time (real) = 131.51 sec

The following tests FAILED:
	  1 - unittest (Not Run)
	  4 - 5 (Failed)
	  5 - 6 (Failed)
	  7 - 10 (Failed)
	 11 - Cohort (Failed)
	 12 - EffectiveDrug (Failed)
	 13 - Empirical (Failed)
	 14 - ESTS (Failed)
	 15 - Genotypes (Failed)
	 17 - KK_20150612 (Failed)
	 18 - Molineaux (Failed)
	 19 - MolPairwise (Failed)
	 20 - MSAT (Failed)
	 22 - NoInterv (Failed)
	 23 - NoMPDLarviciding (Failed)
	 24 - Penny (Failed)
	 26 - SimpleMPDLarviciding (Failed)
	 29 - TrapTest (Failed)
	 30 - VecFullTest (Failed)
	 31 - VecMonthly (Failed)
	 33 - Vivax (Failed)
Errors while running CTest`

**Comment by dhardy** [comment] 2017-08-07 11:02
> Checkpoint test ...

CTest does checkpointing, `run.py` doesn't by default.

Try `python test/run.py Empirical -- --checkpointing`

**Comment by slremy** [comment] 2017-08-07 11:42
Thank for your feedback!
Ok, so I see why there's a difference though now I don't quite get why run.py would produce the same output.txt at all when `--checkpoint` is not used..

```

mbp:build2 user$ python test/run.py Empirical -- --checkpoint
Mon, 07 Aug 2017 14:22:57	/Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml
  /Users/sekou/Documents/source/oli/openmalaria-git/build2/openMalaria --deprecation-warnings --resource-path /Users/sekou/Documents/source/oli/openmalaria-git/test --scenario /Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml --checkpoint
BoincWrapper: not using BOINC
Deprecation warning: model option INCLUDES_PK_PD is no longer used
Deprecation warning: monitoring/surveys: specification of "diagnostic" is suggested over "detectionLimit"
Deprecation warning: time specified via duration "3650" where a date could be used; recommended to use a date (e.g. 2011-12-20)
Deprecation warning: duration "3650" specified without unit; it is recommended to do so (e.g. 5d or 1t or 0.5y)
Deprecation warning: duration "28" specified without unit; it is recommended to do so (e.g. 5d or 1t)
Deprecation warning: specification of the diagnostic used by the Neonatal Mortality model is recommended (model/clinical/neonatalMortality)
[ 45%]	Checkpoint test: checkpoint written; exiting...
OpenMalaria: No such file or directory
  /Users/sekou/Documents/source/oli/openmalaria-git/build2/openMalaria --deprecation-warnings --resource-path /Users/sekou/Documents/source/oli/openmalaria-git/test --scenario /Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml --checkpoint
BoincWrapper: not using BOINC
Deprecation warning: model option INCLUDES_PK_PD is no longer used
Deprecation warning: monitoring/surveys: specification of "diagnostic" is suggested over "detectionLimit"
Deprecation warning: time specified via duration "3650" where a date could be used; recommended to use a date (e.g. 2011-12-20)
Deprecation warning: duration "3650" specified without unit; it is recommended to do so (e.g. 5d or 1t or 0.5y)
Deprecation warning: duration "28" specified without unit; it is recommended to do so (e.g. 5d or 1t)
Deprecation warning: specification of the diagnostic used by the Neonatal Mortality model is recommended (model/clinical/neonatalMortality)
16425t RC
[ 95%]	Checkpoint test: checkpoint written; exiting...
OpenMalaria: No such file or directory
Assertion failed: (measure < measure_map.size()), function report, file /Users/sekou/Documents/source/oli/openmalaria-git/model/mon/mon.cpp, line 292.
Non-zero exit status: -6
```

vs

```

mbp:build2 user$ python test/run.py Empirical
Mon, 07 Aug 2017 14:23:34	/Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml
  /Users/sekou/Documents/source/oli/openmalaria-git/build2/openMalaria --deprecation-warnings --resource-path /Users/sekou/Documents/source/oli/openmalaria-git/test --scenario /Users/sekou/Documents/source/oli/openmalaria-git/test/scenarioEmpirical.xml
BoincWrapper: not using BOINC
Deprecation warning: model option INCLUDES_PK_PD is no longer used
Deprecation warning: monitoring/surveys: specification of "diagnostic" is suggested over "detectionLimit"
Deprecation warning: time specified via duration "3650" where a date could be used; recommended to use a date (e.g. 2011-12-20)
Deprecation warning: duration "3650" specified without unit; it is recommended to do so (e.g. 5d or 1t or 0.5y)
Deprecation warning: duration "28" specified without unit; it is recommended to do so (e.g. 5d or 1t)
Deprecation warning: specification of the diagnostic used by the Neonatal Mortality model is recommended (model/clinical/neonatalMortality)
[ 99%]	sim end
Total/allowed infections: 155809/155809	(0% prevented)
Human updates/total calls: 6282549/7300200	(13.94% skipped)
Done in 12.7798769474 seconds
  compareOutput.py /Users/sekou/Documents/source/oli/openmalaria-git/test/expected/outputEmpirical.txt /Users/sekou/Documents/source/oli/openmalaria-git/build2/test/Empirical-VPoB2b/output.txt 0
output.txt files are identical
```

**Comment by dhardy** [comment] 2017-08-07 12:02
Checkpointing is to allow the simulator to be killed mid-run, then resume from some point just before it was killed (like game saves). The `--checkpoint` option tells OpenMalaria to write a checkpoint then kill itself to test the checkpointing.

**Comment by slremy** [comment] 2017-08-07 15:40
Understood. The part that I'm not clear about is my status on having a working OM installation..
If checkpointing causes my build's tests to fail, and my team mate's C executables (similar build environment) run fine on my machine.. 

I think for now I'd be more comfortable using Ubuntu!

**Comment by dhardy** [comment] 2017-08-07 21:48
Two things are confusing me about your error messages:

> OpenMalaria: No such file or directory

This doesn't seem to be fatal, but may be a problem. It's not clear what.

> Assertion failed: (measure < measure_map.size()), function report, file /Users/sekou/Documents/source/oli/openmalaria-git/model/mon/mon.cpp, line 292.

Probably a programming bug, but I'm not sure what. Either `report()` is called before `init()` due to incorrect resume or `measure` got an incorrect value (likely corruption). Without a debugger it's hard to tell, and it's too long since I've worked on this code.

**Comment by slremy** [comment] 2017-08-08 07:18
Thank you!

**Comment by tph-thuering** [comment] 2017-08-18 13:21
Hi @slremy are you running OM on a MacOS X system? Which version of the operating system, which version or commit/branch of OpenMalaria?

Some hints on the environment would help us to be able to reproduce this behaviour.
Otherwise we cannot debug this remotely ;-).

**Comment by slremy** [comment] 2017-08-18 13:54
Sorry about that!
commit a50730b0d0f45ebde9cae879303b13ec53536483
OSX 10.12.6
Mid 2014 Retina
g++ <Homebrew GCC 6.3.0_1>
Python 2.7.13 <homebrew>

**Comment by tph-thuering** [comment] 2017-08-18 14:42
@slremy Thank you! No offense taken ;-)

I currently do not have an Apple machine ready to test, but anybody who has, please try to reproduce.
ping Melissa via @pemberto ?

**Comment by dhardy** [comment] 2017-10-03 14:00
@slremy I'm going to close this. If you still want us to look into it, then:

1.  Remove old build (`make clean`)
2.  Enable debugging info (pass `-DCMAKE_BUILD_TYPE=Debug` to CMake or change in GUI)
3.  Build (`make`) and test
4.  If it doesn't work, run in a debugger: `python test/run.py Empirical --gdb -- --checkpoint`, type `run` until it crashes, then `bt`

**Closed by dhardy** 2017-10-03 14:00 UTC
